name = "DensityFlows"
uuid = "76bf0c8b-52dc-40eb-a764-102eb4cc7fe0"
authors = ["Ga√©tan Facchinetti"]
version = "1.0.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ChainRulesCore = "1.26.0"
Distributions = "0.25.120"
Documenter = "1.14.1"
Flux = "0.16.4"
JLD2 = "0.6.1"
LinearAlgebra = "1.11.0"
Optimisers = "0.4.6"
Random = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
